<div class="jumbotron">
  
  <div class="page-header">
    <h4>Résumé de la base de donnée</h4>
  </div>

  <div class="row">
    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Etablissements</h5>
    			<span class="label label-info"><?php echo $this->nbrets; ?></span>
    		</div>
    	</div>
    </div>

    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Etudiants</h5>
    			<span class="label label-info"><?php echo $this->nbretu; ?></span>
    		</div>
    	</div>
    </div>

    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Abonnements valides</h5>
    			<span class="label label-info">12</span>
    		</div>
    	</div>
    </div>

    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Annonces</h5>
    			<span class="label label-info">12</span>
    		</div>
    	</div>
    </div>
  </div>

  <div class="page-header">
    <h4>Résumé des demandes et recette</h4>
  </div>

  <div class="row">
    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Demandes</h5>
    			<span class="label label-info">12</span>
    		</div>
    	</div>
    </div>

    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Recette totale</h5>
    			<span class="text-info">12 dollars</span>
    		</div>
    	</div>
    </div>


	<div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Demandes du mois</h5>
    			<span class="label label-info">12</span>
    		</div>
    	</div>
    </div>

    <div class="col-md-6">
    	<div class="thumbnail">
    		<div class="caption">
    			<h5>Recette du mois</h5>
    			<span class="text-info">12 dollars</span>
    		</div>
    	</div>
    </div>


	</div>

</div>