<div class="jumbotron jumblogin">
  <h4 class="h4login">e-valve</h4>
  <form role="form" method="POST" action="<?php echo $this->url(array(),'login',true); ?>">
      <div class="form-group">
          <label for="email">Email : </label> 
          <input type="email" class="form-control input-sm" name="email" id="inputEmail" placeholder="votre email" required>
      </div>
      <div class="form-group">
          <label for="mdp">Mot de passe : </label> 
          <input type="password" class="form-control input-sm" name="mdp" id="inputPassword" placeholder="votre mot de passe" required>
      </div>
      <button type="submit" class="btn btn-danger btn-sm">connexion</button> 
  </form>
</div>