<?php echo $this->doctype(); ?> 

<html>
  
<!-- HEAD
================================================================================================================ -->
<head>
    
<meta charset="utf-8" />
<title><?php echo $this->titre; ?></title>

<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/bootstrap/css/bootstrap.min.php'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/bootstrap/css/sheet.css'); ?>">
    
</head>

<body>

<div class="contenu">
<div class="container error">
  <p>
    <img src="<?php echo $this->baseUrl('/public/img/error.png'); ?>" alt="...">
  </p>

  <h1 class="text-danger">Erreur 404</h1>
  
  <p><?php echo $this->message; ?></p>

  <?php if (isset($this->exception)): ?>
  
  <h3>This part is for the webmaster:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>

</div>

</div>
</body>

</html>
  