<?php echo $this->doctype(); ?> 

<html>
    
<head>
    
<meta charset="utf-8" />
<title><?php echo $this->titre; ?></title>

<?php  
echo $this->cScript('bootstrap.css');
echo $this->cScript('sheet.css');
?>
    
</head>

<body>

<div class="container contlogin">
<?php echo $this->showMessages(); ?>
<?php echo $this->layout()->content; ?>
</div>

<?php  
echo $this->jaScript('bootstrap.min.js');
echo $this->jaScript('jquery.js');
?>

</body>

</html>